apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  pipeline:
    default-timeout-minutes: 240
    default-task-run-workspace-binding: "emptyDir: {}"
  dashboard:
    readonly: false
