apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: scalability
spec:
  limits:
    - default:
        memory: 16Gi
      defaultRequest:
        memory: 8Gi
      type: Container
