apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-class.yaml
  - storage-class-gp2.yaml
  - bucket.yaml
  - operator-install.yaml
  - dashboards.yaml
  - log-server/
  - scalability-ns/
