apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tekton-log-collector
  namespace: tekton-pipelines
  labels:
    app: tekton-log-collector
spec:
  selector:
    matchLabels:
      app: tekton-log-collector
  template:
    metadata:
      labels:
        app: tekton-log-collector
    spec:
      serviceAccountName: tekton-log-server
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.32.0
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/config/fluent-bit.conf"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: config
          mountPath: /config/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: fluentbit-s3-config
